FROM golang:1.20.1-alpine3.17

ENV APP_HOME /go/src/twitchsongrequests

WORKDIR "${APP_HOME}"

COPY . "${APP_HOME}"

RUN go mod download

RUN go mod verify

RUN go build .

# this should match the defaultPort value in main.go since we aren't
# injecting a port value into the docker container
EXPOSE 8000 

CMD ["./twitchsongrequests"]