name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install UI dependencies
        run: npm ci
        working-directory: ./ui
      - name: Build UI
        run: ng build --aot --prod
        shell: bash
        working-directory: ./ui
      - name: Build server
        run: gradle clean assemble testClasses
        shell: bash
        working-directory: ./server
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test UI
        run: ng test
        shell: bash
        working-directory: ./ui
      - name: Test server
        run: gradle test
        shell: bash
        working-directory: ./server
