name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install UI dependencies
        run: npm ci
        working-directory: ./ui
      - name: Install Angular CLI
        run: sudo npm install -g @angular/cli
        working-directory: ./ui
      - name: Build UI
        run: ng build --aot --prod
        shell: bash
        working-directory: ./ui
      - name: Build server
        run: gradle clean assemble testClasses
        shell: bash
        working-directory: ./server
      - name: Build song queue lambda
        run: gradle clean assemble testClasses
        shell: bash
        working-directory: ./queue-song-lambda
  test:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack:latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Localstack AWS configs
        run: |
          mkdir -p ~/.aws
          cp ./.aws/* ~/.aws/
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install UI dependencies
        run: npm ci
        working-directory: ./ui
      - name: Install Angular CLI
        run: sudo npm install -g @angular/cli
      - name: Test UI
        run: ng test
        shell: bash
        working-directory: ./ui
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Test server
        run: gradle test
        shell: bash
        working-directory: ./server
      - name: Test song queue lambda
        run: gradle test
        shell: bash
        working-directory: ./queue-song-lambda
